version: '3'

services:
  app:
    build: .
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
    depends_on:
      - db

  db:
    image: mongo:4.4.5-bionic
    ports:
      - "27017:27017"
