version: '3'

services:
  app:
    image: bismabaig/nodejs:test 
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - db

  db:
    image: mongo:4.4.5-bionic
    ports:
      - "27017:27017"
