version: '3'

services:
  prod:
    image: bismabaig/nodejs:prod-latest
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - MONGO_URL=${MONGO_URL}
    
  dev:
    image: bismabaig/nodejs:dev-latest
    ports: 
      - "3009:3007"
    environment:
      - PORT=3007
      - MONGO_URL=${MONGO_URL}
